-- Values come from installed character BINs (research/katarina/installed).
-- Asset evidence is not live validation. Readiness always comes from the host.
local P={build='2026-09-24-kata-2',classic={id='classic',hero='Jade_Katarina',mapID=453,
    qRange=675,qSpeed=1600,wRange=375,eRange=700,jumpRange=700,rRange=550,rActivation=500,
    qBase={60,85,110,135,160},qAP=.45,wBase={40,75,110,145,180},wAP=.25,wAD=.6,
    eBase={60,85,110,135,160},eAP=.4,eAD=0,markBase={15,30,45,60,75},markAP=.15,
    rBase={40,57.5,75},rAP=.25,rAD=.375,rTicks=4,rDuration=2.5,
    marks={jade_katarinaqbuff=true},channels={jade_katarinarsound=true},rNames={jade_katarinar=true},
    spellNames={[0]={jade_katarinaq=true},[1]={jade_katarinaw=true},[2]={jade_katarinae=true},[3]={jade_katarinar=true}},
    wards={[772043]='stack',[772044]='stack',[772045]='charge',[772049]='charge',[772050]='stack',[773154]='cooldown',[773160]='cooldown',[773340]='charge'},
    wardInventoryCharges={[772045]=true,[772049]=true},yellowWard=773340,
    -- Lower legal E bound retained where castRange=700 disagrees with display=725.
    evidence={eRange='installed castRange; display disagrees',wRange='pinned Classic controller, conservative 375',damage='installed BIN named data; live unverified'}},
    normal={id='normal',hero='Katarina',mapID=11,qRange=625,qSpeed=1800,wRange=340,eRange=725,jumpRange=725,rRange=550,rActivation=500,
    qBase={80,115,150,185,220},qAP=.4,eBase={20,30,40,50,60},eAP=.25,eAD=.4,
    rBase={25,37.5,50},rAP=.19,rTicks=6,rDuration=2.5,rOnHit={.25,.30,.35},
    daggerRadius=340,daggerPickup=140,daggerDuration=4,daggerLand=1.25,eOffset=140,
    channels={katarinarsound=true},rNames={katarinar=true},marks={},wards={},
    spellNames={[0]={katarinaq=true},[1]={katarinaw=true},[2]={katarinaewrapper=true,katarinae=true},[3]={katarinar=true}},
    evidence={eRange='installed KatarinaE and display override',damage='installed named data; physical R and passive level curve separately catalogued'}}}
P.protection={judicatorintervention=true,kayler=true,undyingrage=true,tryndamereundyingrage=true,
    kindredrnodeathbuff=true,zhonyasringshield=true,bardrstasis=true,zileanr=true,zileanchronoshift=true,
    chronoshift=true,willrevive=true,guardianangel=true,aniviapassiverebirth=true}
P.spellShield={bansheesveil=true,sivire=true,nocturneshroudofdarkness=true,malzaharpassiveshield=true}
-- Recognized targeted interrupts only. Classic names are pinned in ClassicAIOv2
-- Fiora's WAttackList; no alias is generated by prefixing a modern name.
P.interrupts={classic={jade_leonashieldofdaybreakattack=true,jade_leonashieldofdaybreak=true,
    jade_blitzcrankpowerfistattack=true,jade_blitzcrankpowerfist=true,jade_garenqattack=true,
    jade_xinzhaoq_thrust3=true,jade_twistedfate_goldcardattack=true},
    normal={leonashieldofdaybreakattack=true,powerfistattack=true,goldcardattack=true}}
function P.select(name)if name=='Jade_Katarina'then return P.classic elseif name=='Katarina'then return P.normal end end
return P
