"""Single maintained ActionClient source; standalone and embedded use identical render."""
from pathlib import Path
R=Path(__file__).resolve().parents[1]
def render():
    p=R/'Scripts/Common/ActionClient'
    parts=['-- GENERATED by build_action_client.py; Actions client v1','local transports={}']
    for name in ('gg','orbama'):
        parts.append('transports["'+name+'"]=(function()\n'+(p/(name+'.lua')).read_text(encoding='utf-8')+'\nend)()')
    parts.append('local create=(function()\n'+(p/'client.lua').read_text(encoding='utf-8')+'\nend)()')
    parts.append('return function(g,options)return create(g or _G,transports,options)end')
    return '\n'.join(parts)
if __name__=='__main__':
    (R/'Scripts/Common/ActionClient.lua').write_text(render(),encoding='utf-8',newline='\n')
