"""Offline deterministic Katarina bundle. Editable modules only; no network."""
from pathlib import Path
import hashlib
import json
ROOT=Path(__file__).resolve().parents[1]

def render_legacy():
    return '-- Generated compatibility entry; KataHari.lua owns the controller.\nreturn require("KataHari")\n'

def render(transform=None, omit=()):
    paths={f'kata.{p.stem}':p for p in (ROOT/'Scripts/Common/Katarina').glob('*.lua')}
    paths.update({f'ChampionMobility.{p.stem}':p for p in (ROOT/'Scripts/Common/ChampionMobility').glob('*.lua')})
    paths['kata.navdata']=ROOT/'Scripts/Common/LeeHarveyOsward/navdata.lua'
    generation=hashlib.sha256((Path(__file__).read_text(encoding='utf-8')+''.join(name+path.read_text(encoding='utf-8')for name,path in sorted(paths.items()))).encode()).hexdigest()
    chunks=['''-- Generated by tools/build_katarina.py; edit Scripts/Common/Katarina.
if not myHero or (myHero.charName~='Katarina' and myHero.charName~='Jade_Katarina') then return end
local function boot()
local generation='KATARINA_GENERATION'
if not SDK or not SDK.OrbamaVersion or not SDK.Actions or not SDK.Actions.GetCapabilities or not SDK.Actions:GetCapabilities().createClient
 or not SDK.Damage or not SDK.TargetSelector or not SDK.SharedData or not SDK.OnTick or not SDK.OnDraw or not SDK.OnWndMsg then
 print('[Kata Hari] Enable Orbama and reload the script runtime.');return
end
local previous=_G.KatarinaController
if previous and previous.active then
 if previous.hero==myHero and previous.sdk==SDK and previous.generation==generation then return previous end
 local ok=pcall(previous.Shutdown,previous,'replacement')
 if not ok or previous.active then return end
end
local modules,cache={},{}
local externalRequire=require
''']
    for name,path in sorted(paths.items()):
        if name in omit:continue
        body=path.read_text(encoding='utf-8')
        if transform:body=transform(name,body)
        chunks.append('modules['+json.dumps(name)+']=function(require)\n'+body+'\nend\n')
    chunks.append('''local function load(name)
 if cache[name]~=nil then return cache[name] end
 if not modules[name] then return externalRequire(name) end
 local value=modules[name](load);cache[name]=value;return value
end
local app
local ok,why=pcall(function()app=load('kata.app').new();app.generation=generation;app:init();app:install()end)
if not ok then if app then pcall(app.Shutdown,app,'load_failed')end;print('[Kata Hari] Load failed: '..tostring(why));return end
local legacy=_G.ClassicAIOv2
if myHero.charName=='Jade_Katarina' and legacy and legacy.enabled then
 local closed=pcall(legacy.Shutdown,legacy,'standalone_katarina')
 if not closed or legacy.enabled then app:Shutdown('legacy_cleanup_failed');return end
end
_G.KatarinaController=app
print('[Kata Hari] Loaded '..app.profile.id..' '..app.build)
return app
end
if not SDK and Callback and Callback.Add and DelayAction then
 -- The provider's Load callback may run after this file was evaluated.
 local pending=true
 Callback.Add('Load',function()
  if pending then pending=false;DelayAction(function()boot()end,.1)end
 end)
 return
end
return boot()
''')
    return ''.join(chunks).replace('KATARINA_GENERATION',generation)

if __name__=='__main__':
    body=render();(ROOT/'Scripts/KataHari.lua').write_text(body,encoding='utf-8',newline='\n')
    (ROOT/'Scripts/Katarina.lua').write_text(render_legacy(),encoding='utf-8',newline='\n')
    print('Kata Hari',hashlib.sha256(body.encode()).hexdigest())
