"""Deterministic single-file Lua bundler."""
from pathlib import Path
import re
import sys

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT / 'tools'))
SOURCE = ROOT / 'Scripts/Common/LeeHarveyOsward'
OUT = ROOT / 'Scripts/LeeHarveyOsward.lua'

def lua(value):
    if value is None: return 'nil'
    if isinstance(value, bool): return 'true' if value else 'false'
    if isinstance(value, (int, float)): return str(value)
    if isinstance(value, str):
        return '"' + value.replace('\\', '\\\\').replace('"', '\\"').replace('\n', '\\n').replace('\r', '') + '"'
    if isinstance(value, list): return '{' + ','.join(map(lua, value)) + '}'
    return '{' + ','.join('[' + lua(k) + ']=' + lua(v) for k, v in value.items()) + '}'

def render_bundle(transform=None, omit=()):
    files=sorted(SOURCE.glob('*.lua'))
    if not (SOURCE/'app.lua').exists(): raise RuntimeError('Missing application entry point')
    build=re.search(r"build='([^']+)'",(SOURCE/'profiles.lua').read_text(encoding='utf-8')).group(1)
    lines=['-- LEE HARVEY OSWARD -- generated by tools/build_lho.py; edit modular sources.\n',
           'if not myHero or (myHero.charName ~= "LeeSin" and myHero.charName ~= "Jade_LeeSin") then return end\n',
           'if not _G.SDK and not _G.GGUpdate then\n'
           ' if not Callback or not Callback.Add then print("[LHO] Game callback API unavailable; enable Orbama and reload."); return end\n'
           ' local ok, err = pcall(function()\n'
           '  if SCRIPT_PATH and type(loadfile) == "function" then\n'
           '   local path = SCRIPT_PATH; if not path:match("[/\\\\]$") then path = path .. "/" end\n'
           '   local loader, reason = loadfile(path .. "Orbama.lua"); assert(loader, reason); loader()\n'
           '  else require("Orbama") end\n'
           ' end)\n'
           ' if not ok or not (_G.SDK and _G.SDK.OrbamaVersion) then print("[LHO] Orbama load failed: " .. tostring(err or "SDK unavailable")); return end\n'
           'end\n',
           'local incomingBuild = '+lua(build)+'\n'
           'local previous = _G.LeeHarveyOsward\n'
           'if previous then\n'
           ' if previous.build == incomingBuild and previous.active then return previous end\n'
           ' if type(previous.Shutdown) ~= "function" then print("[LHO] Older controller cannot be unloaded; restart the script runtime."); return previous end\n'
           ' local ok, err = pcall(previous.Shutdown, previous)\n'
           ' if not ok or previous.active ~= false or _G.LeeHarveyOsward == previous then\n'
           '  print("[LHO] Older controller cleanup failed; restart the script runtime: " .. tostring(err)); return previous\n'
           ' end\n'
           ' print("[LHO] Replacing older controller with " .. incomingBuild)\n'
           'end\n',
           'pcall(require, "GGPrediction")\nlocal modules, cache = {}, {}\nlocal externalRequire = require\n']
    for file in files:
        if file.stem in omit: continue
        body=file.read_text(encoding='utf-8')
        if transform: body=transform(file.stem,body)
        lines.append('modules["lho.'+file.stem+'"] = function(require)\n'+body+'\nend\n')
    from build_action_client import render as render_client
    lines.append('modules["Orbama.menus"] = function(require)\n'+
                 (ROOT/'Scripts/Common/Orbama/menus.lua').read_text(encoding='utf-8')+'\nend\n')
    lines.append('modules["ActionClient"] = function(require)\n'+render_client()+'\nend\n')
    for file in sorted((ROOT/'Scripts/Common/ChampionMobility').glob('*.lua')):
        lines.append('modules["ChampionMobility.'+file.stem+'"] = function(require)\n'+file.read_text(encoding='utf-8')+'\nend\n')
    lines.append('local function load(name)\n if cache[name] ~= nil then return cache[name] end\n'
                 ' local factory = modules[name]\n if not factory then return externalRequire(name) end\n'
                 ' local result = factory(load)\n cache[name] = result\n return result\nend\n'
                 'local function boot()\n'
                 ' if _G.LeeHarveyOsward then return end\n'
                 ' if not _G.SDK or not _G.SDK.Orbwalker or not _G.SDK.Cursor or not _G.SDK.Attack or not _G.SDK.Damage\n'
                 '  or not _G.SDK.OnTick or not _G.SDK.OnDraw or not _G.SDK.OnWndMsg then\n'
                 '  print("[LHO] Enable Orbama or Original-GG before loading Lee Harvey Osward.")\n return end\n'
                 ' local app\n'
                 ' local ok, err = xpcall(function()\n app = load("lho.app").new({originalGG=not _G.SDK.OrbamaVersion})\n app:install()\n end,\n'
                 '  function(e) return debug and debug.traceback and debug.traceback(tostring(e), 2) or tostring(e) end)\n'
                 ' if not ok then\n'
                 '  if app then pcall(app.ctx.log, app.ctx, "controller_error", {reason=tostring(err)}); pcall(app.Shutdown, app) end\n'
                 '  print("[LHO] Load failed: " .. tostring(err)); return\n end\n'
                 ' _G.LeeHarveyOsward = app\nend\n'
                 'if _G.SDK then boot() elseif Callback and Callback.Add then Callback.Add("Load", boot)\n'
                 'else print("[LHO] Game callback API unavailable; enable Orbama and reload.") end\nreturn _G.LeeHarveyOsward\n')
    return ''.join(lines)

def bundle():
    text=render_bundle()
    OUT.write_text(text,encoding='utf-8',newline='\n')
    print(f'Built {OUT.name}: {len(list(SOURCE.glob("*.lua")))} modules, {len(text):,} characters')

if __name__ == '__main__':
    bundle()
