"""Deterministic lexical bundler; never changes the host global environment."""
from pathlib import Path
import sys
R=Path(__file__).resolve().parents[1]
sys.path.insert(0,str(R/'tools'))
from build_action_client import render as client
def render(library=False, transform=None):
    parts=['-- Generated by tools/build_evade.py; edit Scripts/Common/OrbamaEvade.',
           'local modules,cache={},{};local externalRequire=require']
    for p in sorted((R/'Scripts/Common/OrbamaEvade').glob('*.lua')):
        body=p.read_text(encoding='utf-8')
        if transform:body=transform(p.stem,body)
        parts.append('modules["evade.'+p.stem+'"] = function(require)\n'+body+'\nend')
    parts.append('modules.ActionClient=function(require)\n'+client()+'\nend')
    parts.append('local function load(name) if cache[name]~=nil then return cache[name]end; local f=modules[name]; if not f then return externalRequire(name)end; local v=f(load);cache[name]=v;return v end')
    parts.append('return load' if library else 'return load("evade.app").boot(_G)')
    return '\n'.join(parts)+'\n'
if __name__=='__main__':
    out=R/'Scripts/OrbamaEvade.lua';out.write_text(render(),encoding='utf-8',newline='\n');print(out)
