"""Deterministic, lexical Lua 5.1 / LuaJIT TF bundle. No environment reassignment."""
from pathlib import Path
import hashlib
ROOT=Path(__file__).resolve().parents[1]
SOURCE=ROOT/'Scripts/Common/TwistedFate'
OUT=ROOT/'Scripts/CardMarx.lua'
LEGACY=ROOT/'Scripts/TwistedFate.lua'
def render_legacy():
    return '-- Generated compatibility entry; CardMarx.lua owns the controller.\nreturn require("CardMarx")\n'
def render(transform=None, omit=()):
    files=sorted(SOURCE.glob('*.lua'))
    bodies={f'tf.{f.stem}':f.read_text(encoding='utf-8') for f in files}
    bodies['CombatProfiles.twisted_fate']=(ROOT/'Scripts/Common/CombatProfiles/twisted_fate.lua').read_text(encoding='utf-8')
    fingerprint=hashlib.sha256(''.join(bodies.values()).encode()).hexdigest()
    result=['-- Generated by tools/build_twisted_fate.py; edit modular sources.\n',
        'if not myHero or (myHero.charName~="TwistedFate" and myHero.charName~="Jade_TwistedFate") then return end\n',
        'if not (_G.SDK and SDK.OrbamaVersion) then print("[CardMarx] Load Orbama first; reload the complete runtime."); return end\n',
        'if not SDK.Actions or not SDK.Actions.GetCapabilities or not SDK.Actions:GetCapabilities().createClient\n'
        ' or not SDK.SharedData or not SDK.OnUrgent or not SDK.Attack or not SDK.Damage or not SDK.Damage.GetTwistedFateAttack then\n'
        ' print("[CardMarx] Required Orbama capabilities unavailable."); return end\n',
        'local fingerprint="'+fingerprint+'"\n',
        'local previous=_G.OrbamaTwistedFate\n'
        'if previous then\n'
        ' if previous.active and previous.fingerprint==fingerprint then return previous end\n'
        ' print("[CardMarx] Another TF instance exists; reload the complete runtime."); return previous\nend\n',
        'pcall(require,"GGPrediction")\nlocal modules,cache={},{}\nlocal externalRequire=require\n']
    for name,body in bodies.items():
        if name in omit:continue
        if transform:body=transform(name,body)
        result.append('modules["'+name+'"] = function(require)\n'+body+'\nend\n')
    result.append('local function load(name)\n'
        ' if cache[name]~=nil then return cache[name] end\n'
        ' local factory=modules[name];if not factory then return externalRequire(name) end\n'
        ' local value=factory(load);cache[name]=value;return value\nend\n'
        'local app\nlocal ok,err=pcall(function()app=load("tf.app").new();app:initialize();app.fingerprint=fingerprint;app:install()end)\n'
        'if not ok then if app then app:Shutdown()end;print("[CardMarx] Load failed: "..tostring(err));return end\n'
        '_G.OrbamaTwistedFate=app\nreturn app\n')
    return ''.join(result)
if __name__=='__main__':
    body=render();OUT.write_text(body,encoding='utf-8',newline='\n');print(f'Built {OUT.name}: {len(body):,} characters')
    LEGACY.write_text(render_legacy(),encoding='utf-8',newline='\n')
